class_name MapBuilder
extends RefCounted
## Turns the ASCII rows of a map JSON into two TileMapLayers (ground + decor) and a list of
## props to spawn. One TileSet, three atlas sources:
##   0  assets/tiles/tileset.png          interior floors/walls (generated by tools/make_tileset.py)
##   1  Lakiiah "Ground Tiles.png"        grass, path, tilled soil, cliff, bushes, rocks, flowers
##   2  Lakiiah "House Tiles.png"         fences, signpost, barrel (houses are props, see Prop)
##
## Ground legend:  , grass   = path (autotiled)   ~ tilled soil (autotiled)   C cliff top   D dirt
##                 . wood floor   : tiled floor   # wall   c carpet   _ door mat   T grass + tree prop
## Decor legend:   T tree   f wooden fence   F stone fence   G light stone fence (all autotiled)
##                 b bush   B berry bush   s small bush   r rocks   R big rock   o pebble
##                 * blue flowers   + red flowers   ' orange flowers   m mushroom   S signpost   l barrel

const TILE := 16
const SRC_INTERIOR := 0
const SRC_GROUND := 1
const SRC_HOUSE := 2
const GROUND_TEX := "res://assets/Cozy RPG Tileset - Lakiiah/TopDown 16x16/Ground Tiles.png"
const HOUSE_TEX := "res://assets/Cozy RPG Tileset - Lakiiah/TopDown 16x16/House Tiles.png"
const INTERIOR_TEX := "res://assets/tiles/tileset.png"

enum I { WOOD, WALL, CARPET, MAT, TILED }

const GRASS_VARIANTS := [
	Vector2i(1, 1), Vector2i(2, 1), Vector2i(3, 1), Vector2i(1, 2), Vector2i(2, 2),
	Vector2i(3, 2), Vector2i(3, 2), Vector2i(3, 2), Vector2i(3, 2), Vector2i(1, 3), Vector2i(2, 3), Vector2i(3, 3),
]
const CLIFF_TOP := Vector2i(7, 4)
const DIRT := Vector2i(7, 5)
const PATH_BLOCK := Vector2i(12, 0)
const PATH_V_COL := 11
const PATH_H_ROW := 3
const SOIL_BLOCK := Vector2i(8, 0)
const DECOR := {
	"b": [Vector2i(10, 4), true], "B": [Vector2i(11, 4), true], "s": [Vector2i(12, 4), true],
	"r": [Vector2i(10, 5), true], "R": [Vector2i(11, 5), true], "o": [Vector2i(12, 5), false],
	"*": [Vector2i(10, 6), false], "+": [Vector2i(11, 6), false], "'": [Vector2i(12, 6), false],
	"m": [Vector2i(15, 6), false],
}
const HOUSE_DECOR := {"S": [Vector2i(8, 1), true], "l": [Vector2i(10, 1), true]}
const FENCE_BASE := {"f": 13, "F": 17, "G": 21}

static var _tileset: TileSet


static func tileset() -> TileSet:
	if _tileset == null:
		_tileset = _build_tileset()
	return _tileset


static func _build_tileset() -> TileSet:
	var ts := TileSet.new()
	ts.tile_size = Vector2i(TILE, TILE)
	ts.add_physics_layer()
	var interior := _atlas(ts, SRC_INTERIOR, INTERIOR_TEX, I.size(), 1)
	_solid(interior, Vector2i(I.WALL, 0))
	var ground := _atlas(ts, SRC_GROUND, GROUND_TEX, 16, 8)
	_solid(ground, CLIFF_TOP)
	_solid(ground, DIRT)
	for ch in DECOR:
		if DECOR[ch][1]:
			_solid(ground, DECOR[ch][0])
	var house := _atlas(ts, SRC_HOUSE, HOUSE_TEX, 28, 8)
	for col in range(13, 25):
		for row in range(2, 6):
			_solid(house, Vector2i(col, row))
	for ch in HOUSE_DECOR:
		if HOUSE_DECOR[ch][1]:
			_solid(house, HOUSE_DECOR[ch][0])
	return ts


static func _atlas(ts: TileSet, id: int, path: String, cols: int, rows: int) -> TileSetAtlasSource:
	var src := TileSetAtlasSource.new()
	src.texture = load(path)
	src.texture_region_size = Vector2i(TILE, TILE)
	ts.add_source(src, id)  # attach first so tile data knows about the physics layer
	for y in rows:
		for x in cols:
			src.create_tile(Vector2i(x, y))
	return src


static func _solid(src: TileSetAtlasSource, coords: Vector2i) -> void:
	var td := src.get_tile_data(coords, 0)
	if td.get_collision_polygons_count(0) > 0:
		return
	var h := TILE / 2.0
	td.add_collision_polygon(0)
	td.set_collision_polygon_points(0, 0, PackedVector2Array([
		Vector2(-h, -h), Vector2(h, -h), Vector2(h, h), Vector2(-h, h),
	]))


static func build(ground: TileMapLayer, decor: TileMapLayer, data: Dictionary) -> Dictionary:
	## Fills both layers. Returns {"size": Vector2i, "props": [{"sprite", "x", "y"}, ...]}.
	var rows: Array = data.get("rows", [])
	var decor_rows: Array = data.get("decor", [])
	ground.tile_set = tileset()
	decor.tile_set = tileset()
	ground.clear()
	decor.clear()
	var width := 0
	var props: Array = []
	for y in rows.size():
		var row := str(rows[y])
		width = maxi(width, row.length())
		for x in row.length():
			var ch := row[x]
			_set_ground(ground, rows, x, y, ch)
			if ch == "T":
				props.append({"sprite": "tree", "x": x, "y": y})
	for y in decor_rows.size():
		var row := str(decor_rows[y])
		for x in row.length():
			var ch := row[x]
			var cell := Vector2i(x, y)
			if ch == "T":
				props.append({"sprite": "tree", "x": x, "y": y})
			elif FENCE_BASE.has(ch):
				decor.set_cell(cell, SRC_HOUSE, _fence_cell(decor_rows, x, y, ch, FENCE_BASE[ch]))
			elif DECOR.has(ch):
				decor.set_cell(cell, SRC_GROUND, DECOR[ch][0])
			elif HOUSE_DECOR.has(ch):
				decor.set_cell(cell, SRC_HOUSE, HOUSE_DECOR[ch][0])
	return {"size": Vector2i(width, rows.size()), "props": props}


static func _char_at(rows: Array, x: int, y: int) -> String:
	if y < 0 or y >= rows.size():
		return ""
	var r := str(rows[y])
	if x < 0 or x >= r.length():
		return ""
	return r[x]


static func _set_ground(layer: TileMapLayer, rows: Array, x: int, y: int, ch: String) -> void:
	var cell := Vector2i(x, y)
	match ch:
		".":
			layer.set_cell(cell, SRC_INTERIOR, Vector2i(I.WOOD, 0))
		":":
			layer.set_cell(cell, SRC_INTERIOR, Vector2i(I.TILED, 0))
		"#":
			layer.set_cell(cell, SRC_INTERIOR, Vector2i(I.WALL, 0))
		"c":
			layer.set_cell(cell, SRC_INTERIOR, Vector2i(I.CARPET, 0))
		"_":
			layer.set_cell(cell, SRC_INTERIOR, Vector2i(I.MAT, 0))
		"=":
			layer.set_cell(cell, SRC_GROUND, _path_cell(rows, x, y))
		"~":
			layer.set_cell(cell, SRC_GROUND, _auto3(SOIL_BLOCK, rows, x, y, "~"))
		"C":
			layer.set_cell(cell, SRC_GROUND, CLIFF_TOP)
		"D":
			layer.set_cell(cell, SRC_GROUND, DIRT)
		_:
			var i := absi(x * 7 + y * 13 + x * y) % GRASS_VARIANTS.size()
			layer.set_cell(cell, SRC_GROUND, GRASS_VARIANTS[i])


static func _neighbours(rows: Array, x: int, y: int, ch: String) -> Array:
	## [left, right, up, down] booleans: is the same character there?
	return [
		_char_at(rows, x - 1, y) == ch, _char_at(rows, x + 1, y) == ch,
		_char_at(rows, x, y - 1) == ch, _char_at(rows, x, y + 1) == ch,
	]


static func _path_cell(rows: Array, x: int, y: int) -> Vector2i:
	var n := _neighbours(rows, x, y, "=")
	var l: bool = n[0]
	var r: bool = n[1]
	var u: bool = n[2]
	var d: bool = n[3]
	if not l and not r and not u and not d:
		return Vector2i(9, PATH_H_ROW)
	if not l and not r:
		return Vector2i(PATH_V_COL, 0 if not u else (2 if not d else 1))
	if not u and not d:
		return Vector2i(8 if not l else (10 if not r else 9), PATH_H_ROW)
	return _auto3(PATH_BLOCK, rows, x, y, "=")


static func _auto3(block: Vector2i, rows: Array, x: int, y: int, ch: String) -> Vector2i:
	## 3x3 block autotile: borders on the sides that have no same-type neighbour.
	var n := _neighbours(rows, x, y, ch)
	var cx := 1
	if not n[0] and n[1]:
		cx = 0
	elif n[0] and not n[1]:
		cx = 2
	var cy := 1
	if not n[2] and n[3]:
		cy = 0
	elif n[2] and not n[3]:
		cy = 2
	return block + Vector2i(cx, cy)


static func _fence_cell(rows: Array, x: int, y: int, ch: String, base_col: int) -> Vector2i:
	## Pieces are laid out like the wooden fence block at columns 13-16, rows 2-5.
	var n := _neighbours(rows, x, y, ch)
	var l: bool = n[0]
	var r: bool = n[1]
	var u: bool = n[2]
	var d: bool = n[3]
	var c: Vector2i
	if l and r and not u and not d:
		c = Vector2i(15, 2)
	elif u and d and not l and not r:
		c = Vector2i(13, 4)
	elif r and d and not l and not u:
		c = Vector2i(14, 3)
	elif l and d and not r and not u:
		c = Vector2i(16, 3)
	elif r and u and not l and not d:
		c = Vector2i(14, 5)
	elif l and u and not r and not d:
		c = Vector2i(16, 5)
	elif r and not l and not u and not d:
		c = Vector2i(14, 2)
	elif l and not r and not u and not d:
		c = Vector2i(16, 2)
	elif d and not u and not l and not r:
		c = Vector2i(13, 3)
	elif u and not d and not l and not r:
		c = Vector2i(13, 5)
	elif l and r:
		c = Vector2i(15, 2)
	elif u and d:
		c = Vector2i(13, 4)
	else:
		c = Vector2i(13, 3)
	return c + Vector2i(base_col - 13, 0)


static func cell_to_world(cell: Vector2i) -> Vector2:
	return Vector2(cell) * TILE + Vector2(TILE / 2.0, TILE / 2.0)


static func point_to_world(cell: Vector2) -> Vector2:
	## Fractional cells are allowed (a 4-tile-wide house centred on a 2-tile path).
	return cell * TILE + Vector2(TILE / 2.0, TILE / 2.0)
