class_name MapBuilder
extends RefCounted
## Turns the ASCII rows of a map JSON into a TileMapLayer, using a TileSet built at
## runtime from assets/tiles/tileset.png (generated by tools/make_tileset.py).

const TILE := 16
enum T { GRASS, FLOOR, WALL, PATH, SOIL, WATER, TREE, MAT, CARPET }
const LEGEND := {
	",": T.GRASS, " ": T.GRASS,
	".": T.FLOOR,
	"#": T.WALL,
	"=": T.PATH,
	"~": T.SOIL,
	"w": T.WATER,
	"T": T.TREE,
	"_": T.MAT,
	"c": T.CARPET,
}
const SOLID := [T.WALL, T.WATER, T.TREE]

static var _tileset: TileSet


static func tileset() -> TileSet:
	if _tileset == null:
		_tileset = _build_tileset()
	return _tileset


static func _build_tileset() -> TileSet:
	var ts := TileSet.new()
	ts.tile_size = Vector2i(TILE, TILE)
	ts.add_physics_layer()
	var src := TileSetAtlasSource.new()
	src.texture = load("res://assets/tiles/tileset.png")
	src.texture_region_size = Vector2i(TILE, TILE)
	ts.add_source(src, 0)  # attach first so tile data knows about the physics layer
	var half := TILE / 2.0
	for i in T.size():
		var coords := Vector2i(i, 0)
		src.create_tile(coords)
		if i in SOLID:
			var td := src.get_tile_data(coords, 0)
			td.add_collision_polygon(0)
			td.set_collision_polygon_points(0, 0, PackedVector2Array([
				Vector2(-half, -half), Vector2(half, -half), Vector2(half, half), Vector2(-half, half),
			]))
	return ts


static func fill_layer(layer: TileMapLayer, rows: Array) -> Vector2i:
	## Returns the map size in cells.
	layer.tile_set = tileset()
	layer.clear()
	var width := 0
	for y in rows.size():
		var row := str(rows[y])
		width = maxi(width, row.length())
		for x in row.length():
			var t: int = LEGEND.get(row[x], T.GRASS)
			layer.set_cell(Vector2i(x, y), 0, Vector2i(t, 0))
	return Vector2i(width, rows.size())


static func cell_to_world(cell: Vector2i) -> Vector2:
	return Vector2(cell) * TILE + Vector2(TILE / 2.0, TILE / 2.0)
